version: '3.8'

services:
  email-catch-test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2525:2525"
      - "2526:2526"
      - "2527:2527"
      - "2528:2528"
    volumes:
      - ./config:/app/config
      - ./test-emails:/app/test-emails
      - ./logs:/app/logs
    environment:
      - CONFIG_FILE=/app/config/test-config.yaml
    depends_on:
      - minio-test
      - webhook-mock
    networks:
      - test-network

  minio-test:
    image: minio/minio:latest
    ports:
      - "9001:9000"
      - "9002:9001"
    environment:
      - MINIO_ROOT_USER=testuser
      - MINIO_ROOT_PASSWORD=testpass
    command: server /data --console-address ":9001"
    volumes:
      - test_minio_data:/data
    networks:
      - test-network

  webhook-mock:
    image: mockserver/mockserver:latest
    ports:
      - "3000:1080"
    environment:
      - MOCKSERVER_SERVER_POST=1080
    networks:
      - test-network

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    depends_on:
      - email-catch-test
    networks:
      - test-network
    command: ["go", "test", "./tests/integration/...", "-v"]

volumes:
  test_minio_data:

networks:
  test-network:
    driver: bridge