FROM golang:1.21-alpine

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o test-email-sender ./tests/scripts/test_email_sender.go

CMD ["go", "test", "./tests/...", "-v"]